apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xmyfirstcompositeresources.acme.example.org
spec:
  connectionSecretKeys:
    - kubeconfig
  group: acme.example.org
  names:
    kind:     XMyFirstCompositeResource
    plural:   xmyfirstcompositeresources
#  claimNames:           # Claims are namespaced Objects
#    kind:     MyFirstCompositeResource
#    plural:   myfirstcompositeresources
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          description: A Simple CompositeResource Example
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  description: number of replicas to roll out
