---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state
rules:
- apiGroups: ["kubernetes.crossplane.io"]
  resources: ["*"]
  verbs: ["list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-kube-state-metrics-mega-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state
subjects:
- kind: ServiceAccount
  name: prometheus-kube-state-metrics
  namespace: prometheus

