apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consumer
rules:
- apiGroups:
  - "acme.example.org"
  resources:
  - myfirstcompositeresources
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update
