kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devopsconcrossplane
  namespace: rbac-crossplane
subjects:
- kind: User
  name: devopscon
roleRef:
  kind: ClusterRole
  name: consumer
  apiGroup: rbac.authorization.k8s.io

